---
name: CPANPLUS-Dist-SUSE
version: 0.01
author:
  - 'Qindel Formacion y Servicios, SL <Nito@Qindel.ES>'
abstract: To build RPM files from cpan for SUSE
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPANPLUS::Dist::RPM: 0
  CPANPLUS::Error: 0
  English: 0
  IPC::Cmd: 0
  Path::Class: 0
  SUPER: 0
build_requires:
  Test::More: 0
provides:
  CPANPLUS::Dist::SUSE:
    file: lib/CPANPLUS/Dist/SUSE.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
